version: '3.8'

services:
  omcgill:
    build:
      context: .
    container_name: omcgill
    ports:
      - "5001:5001"
      - "5002:5002"
    env_file:
      - .env
    volumes:
      - ./mcgill-chat-frontend/cert.pem:/app/mcgill-chat-backend/.cert/cert.pem
      - ./mcgill-chat-frontend/key.pem:/app/mcgill-chat-backend/.cert/key.pem
    restart: unless-stopped